project:
  name: aws-ocp
  owner: quickstart-eng@amazon.com
  package_lambda: false
  regions:
    - us-west-2

tests:
#  aws-ocp-master:
#    parameter_input: aws-ocp-master.json
#    template_file: aws-ocp-master.template.yaml
#    regions:
#      - us-west-2
  aws-ocp-3-11:
    parameters:
      KeyPairName: "$[taskcat_getkeypair]"
      RemoteAccessCIDR: "0.0.0.0/16"
      AccessCIDR: "0.0.0.0/16"
      StudentNum: "$[taskcat_random-numbers]"
      QSS3BucketName: "$[taskcat_autobucket]"
      QSS3KeyPrefix: "aws-ocp/"
    template: templates/aws-ocp-student-env.template.yaml
    regions:
      - us-west-2
