apiVersion: v1
baseDomain: openshift.awsworkshop.io
compute:
- hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: 1
metadata:
  creationTimestamp: null
  name: trace3-test3 # This must match your taskcat.yaml clustername
networking:
  clusterNetwork:
  - cidr: 10.32.0.0/16
    hostPrefix: 23
  networkType: OpenShiftSDN
  serviceNetwork:
  - 172.30.0.0/16
platform:
  none: {}
pullSecret: "{ 'UpdateMe': true }"
sshKey: |
  ssh-rsa {{ yourkey }}
