AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS Red Hat OCP Master deployment'
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: Security configuration
        Parameters:
          - KeyPairName
          - AccessCIDR
          - RemoteAccessCIDR
      - Label:
          default: Network configuration
        Parameters:
          - AvailabilityZone
          - VPCCIDR
          - PublicSubnetCIDR          
      - Label:
          default: Lab information
        Parameters:
          - OpenShiftVersion
          - NumStudents
      - Label:
          default: Cloud9 information
        Parameters:
          - Cloud9AutoStopInMin
          - Cloud9InstanceType
      - Label:
          default: AWS Quick Start Configuration
        Parameters:
          - LambdaZipsBucketName
          - QSS3BucketName
          - QSS3KeyPrefix
    ParameterLabels:
      AvailabilityZone:
        default: Availability Zone
      KeyPairName:
        default: SSH key name
      PublicSubnetCIDR:
        default: Public subnet CIDR
      AccessCIDR:
        default: Permitted IP range
      RemoteAccessCIDR:
        default: Remote access CIDR 
      VPCCIDR:
        default: VPC CIDR
      OpenShiftVersion:
        default: OpenShift version
      NumStudents:
        default: Number of students
      Cloud9AutoStopInMin:
        default: Cloud9 automatic stop time in minutes
      Cloud9InstanceType:
        default: Cloud9 instance type
      LambdaZipsBucketName:
        default: Lambda zips bucket name
      QSS3BucketName:
        default: Quick Start S3 bucket name
      QSS3KeyPrefix:
        default: Quick Start S3 key prefix          
Parameters:
  VPCCIDR:
    Description: The CIDR block for the VPC.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/27
    Type: String
  AvailabilityZone:
    Description: The Availability Zone to use for the public subnet in the VPC.
    Default: us-west-2a
    Type: AWS::EC2::AvailabilityZone::Name
  KeyPairName:
    Description: The name of an existing public/private key pair, 
      which allows you to connect securely to your instance after it launches. 
      This is the key pair you created in your preferred region.
    Type: AWS::EC2::KeyPair::KeyName
  PublicSubnetCIDR:
    Description: The CIDR block for the public (DMZ) subnet 1 located in Availability
      Zone 1.
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/(1[6-9]|2[0-8]))$
    ConstraintDescription: CIDR block parameter must be in the form x.x.x.x/16-28
    Default: 10.0.0.0/28
    Type: String
  AccessCIDR:
    Description: The CIDR IP range that is permitted to access OpenShift UI and API. 
      We recommend that you set this value to a trusted IP range. 
      For example, you might want to grant only your corporate network access to the software. 
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
  RemoteAccessCIDR:
    Description: The remote CIDR range for allowing SSH into the Cloud9 instance. 
      We recommend that you set this value to a trusted IP range. 
      For example, you might want to grant specific ranges inside your corporate network SSH access. 
    AllowedPattern: ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])(\/([0-9]|[1-2][0-9]|3[0-2]))$
    Type: String
  OpenShiftVersion:
    Description: The version of OpenShift to deploy for the lab.
    AllowedValues:
      - "3.11"
      - "4.2"
    Default: "3.11"
    Type: String
  NumStudents:
    Description: The number of student environments to provision for the lab.
    Default: 1
    Type: Number
  Cloud9AutoStopInMin:
    Description: The time the Cloud9 instance is automatically stopped after no use.
    Default: 30
    Type: Number
  Cloud9InstanceType:
    Description: Instance size of the Cloud9 instance for the student
    AllowedPattern: ^[a-z][1-9][.][a-z0-9]+$
    MinLength: '5'
    MaxLength: '20'
    Default: "t2.micro"
    Type: String
  LambdaZipsBucketName:
    Description: '[OPTIONAL] The name of the S3 bucket where the Lambda zip files should be placed. If you leave this parameter blank, an S3 bucket will be created.'
    Default: ''
    Type: String
  QSS3BucketName:
    Description: S3 bucket name for the Quick Start assets. This string can include
      numbers, lowercase letters, uppercase letters, and hyphens (-). It cannot start
      or end with a hyphen (-).
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    ConstraintDescription: Quick Start bucket name can include numbers, lowercase
      letters, uppercase letters, and hyphens (-). It cannot start or end with a hyphen
      (-).
    Default: aws-quickstart
    Type: String
  QSS3KeyPrefix:
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), and
      forward slash (/).
    AllowedPattern: ^[0-9a-zA-Z-/]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), and forward slash (/).
    Default: aws-ocp/
    Type: String
Conditions:
      CreateLambdaZipsBucket: !Equals [!Ref 'LambdaZipsBucketName', '']
Resources:
  IamStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/aws-ocp-iam.template.yaml'
      Parameters:
        LambdaZipsBucketName: !If [ CreateLambdaZipsBucket, !Ref LambdaZipsBucket, !Ref LambdaZipsBucketName ]
        DeleteLambdaZipsBucketContents: !If [ CreateLambdaZipsBucket, "True", "False" ]
  LambdaZipsBucket:
    Type: AWS::S3::Bucket
    Condition: CreateLambdaZipsBucket

  LambdaStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub 'https://${QSS3BucketName}.s3.amazonaws.com/${QSS3KeyPrefix}templates/aws-ocp-lambda.template.yaml'
      Parameters:
        ExecuteCFRoleArn: !GetAtt IamStack.Outputs.ExecuteCFRoleArn
#  DeleteBucketContents:
#    Condition: CreateLambdaZipsBucket
#    Type: Custom::DeleteBucketContents
#    Version: '1.0'
#    Properties:
#      ServiceToken: !GetAtt 'FunctionStack.Outputs.DeleteBucketContentsLambdaArn'
#      OutputBucket: !Ref 'LambdaZipsBucket'
