AWSTemplateFormatVersion: "2010-09-09"
Description: Deploys Lambda to generate ignition files for OCP lab
Parameters:
  ProjectName:
    Description: Project name
    Type: String
  LambdaZipsBucketName:
    Description: Bucket Name where the lambda zip files should be placed
    Type: String
  QSS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z-/.]*$
    ConstraintDescription: Quick Start key prefix can include numbers, lowercase letters,
      uppercase letters, hyphens (-), dots(.) and forward slash (/).
    Default: aws-ocp/
    Description: S3 key prefix for the Quick Start assets. Quick Start key prefix
      can include numbers, lowercase letters, uppercase letters, hyphens (-), dots(.) and
      forward slash (/).
    Type: String
Resources:
  GenerateIgnitionFilesLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
  GenerateIgnitionFilesLambda:
    Type: AWS::Lambda::Function
    Properties:
      Description: Generates Ignition Files for OpenShift CoreOS deployments
      Handler: lambda_function.handler
      MemorySize: 512
      Runtime: python3.7
      Timeout: 900
      Role: !GetAtt GenerateIgnitionFilesLambdaRole.Arn
      Code:
        S3Bucket: !Ref LambdaZipsBucketName
        S3Key: !Sub '${LambdaZipsBucketName}/${ProjectName}/functions/packages/GenerateIgnitionFiles/lambda.zip'
