global:
  marketplace-ami: false
  owner: quickstart-eng@amazon.com
  qsname: aws-ocp
  regions:
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
    - ca-central-1
    - eu-central-1
    - eu-west-1
    - sa-east-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
 
tests:
  aws-ocp-master:
    parameter_input: aws-ocp-master.json
    template_file: aws-ocp-master.template.yaml
    regions:
      - us-west-2
#  aws-ocp-3-11:
#    parameter_input: aws-ocp-3-11.json
#    template_file: aws-ocp-student-env.template.yaml
#    regions:
#      - us-west-2

